# see https://github.com/adityatelange/hugo-PaperMod/wiki

baseURL: "https://nicolaiarocci.com"
title: Nicola Iarocci
theme: PaperMod
# paginate: 5

permalinks:
  post: /:slug/

enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: false
copyright: Produced / Written / Maintained by [Nicola Iarocci](/) since 2010

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Nicola Iarocci
  description: "This is the personal website of Nicola Iarocci, Software Craftsman."
  # keywords: [Blog, Portfolio, PaperMod]
  # author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["images/avatar.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowFullTextinRSS: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: images/favicon.ico
    favicon16x16: images/favicon16x16.ico
    favicon32x32: images/favicon32x32.ico
    apple_touch_icon: images/favicon.ico
    safari_pinned_tab: images/favicon.ico

  label:
    text: Home
    icon: images/avatar.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: post
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: Nicola Iarocci
    Content: >
      I’m a coder-at-heart author of several [open-source projects](/opensource/), a [Microsoft MVP](https://mvp.microsoft.com/en-US/mvp/profile/a6892d61-aea0-e511-8114-c4346bac0abc), a [speaker](/speaking/), and sometimes a teacher. 
      I co-founded CIR 2000, where I proudly lead the development of [Amica 20](https://gestionaleamica.com/), a hybrid (cloud and on-premise) accounting app for Italian small businesses. 
      I like hiking, [reading good books](/books-i-have-read/), and riding my Triumph Bonneville.

  socialIcons:
    - name: github
      url: "https://github.com/nicolaiarocci"
    - name: twitter
      url: "https://twitter.com/nicolaiarocci"
    - name: mastodon
      url: "https://fosstodon.org/@nicola"
    - name: email
      url: "https://buttondown.email/nicolaiarocci"
    - name: rss
      url: "https://nicolaiarocci.com/index.xml"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/nicolaiarocci/nicolaiarocci.com/tree/master/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    #- name: about
    #  url: /about/
    #  weight: 5
    - name: code
      url: /opensource/
      weight: 10
    - name: speaking
      url: /speaking/
      weight: 20
    - name: library
      url: /books-i-have-read/
      weight: 30
    - name: newsletter
      url: https://buttondown.email/nicolaiarocci
      weight: 40
    - name: rss
      url: /index.xml
      weight: 50
    - name: archive
      url: /archives/
      weight: 60
    - name: search
      url: /search/
      weight: 70

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    noClasses: true
    # anchorLineNos: true
    # lineNos: true
    style: bw